### ISSUE TITLE
glTF Models Not Loading

### ISSUE THREAD

**Issue by MacrayBlackhand** [x3dom/x3dom#1317]
I'm seeing this error with this build:

 * X3DOM 1.8.3-dev
 * Build : 7687
 * Revision: 3b57b30f27c396360d53b1c7a31338b25ff1befe
 * Date: Mon Jun 20 19:37:29 2022 -0400

x3dom-full.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'buffer')
    at x3dom.glTF2Loader._bufferURI (x3dom-full.js:7:451370)
    at x3dom.glTF2Loader._generateX3DBufferGeometry (x3dom-full.js:7:446723)
    at x3dom.glTF2Loader._generateX3DShape (x3dom-full.js:7:440666)
    at x3dom.glTF2Loader._generateX3DNode (x3dom-full.js:7:438089)
    at x3dom.glTF2Loader._traverseNodes (x3dom-full.js:7:437568)
    at x3dom.glTF2Loader.load (x3dom-full.js:7:435859)
    at s.onreadystatechange (x3dom-full.js:7:724143)

Anyone have any ideas?

**Comment by andreasplesch** [comment]
Happy to look into this. Can you share an example ?

**Comment by andreasplesch** [comment]
Feel free to reopen as the need arises.
