### ISSUE TITLE
VolumeData and IsoSurfaceVolumeData ERROR: Assertion failed

### ISSUE THREAD

**Issue by ixakalabadie** [x3dom/x3dom#1326]
Hello, I'm trying to create iso-surfaces with _IsoSurfaceVolumeData_ and I get the following error: "ERROR: Assertion failed in : Unknown shader part type!". I get the following in the console:
```
Uncaught TypeError: Cannot read properties of null (reading '_vf')
    at Object.nodeChanged (x3dom-full.js:7:1289426)
    at Object.setupTree (x3dom-full.js:7:147530)
    at Object.<anonymous> (x3dom-full.js:7:147455)
    at NodeList.forEach (<anonymous>)
    at Object.setupTree (x3dom-full.js:7:147423)
    at Object.<anonymous> (x3dom-full.js:7:147455)
    at NodeList.forEach (<anonymous>)
    at Object.setupTree (x3dom-full.js:7:147423)
    at Object.<anonymous> (x3dom-full.js:7:147455)
    at NodeList.forEach (<anonymous>)
```

I'm using a nrrd file that has worked in tests with X_ITE with a similar code, but I would prefer to use X3DOM since I have already used it in another project. The same happens when I try using _VolumeData_.

Here is the code of my HTML file:

```
<!DOCTYPE html>
<head>
	<script type='text/javascript' src='https://x3dom.org/download/dev/x3dom-full.js'></script>
	<link rel='stylesheet' type='text/css' href='https://x3dom.org/download/dev/x3dom.css'></link>
	<title> Stephan's Quintet</title>
</head>
<body>
	<h1> Stephan's Quintet </h1>
	<center><x3d showStat='true' showLog='true' width='100%' height='500px' id='cubeFixed'>
		<Scene>
			<Viewpoint description='HCG91' position='0 0 200' orientation='0 0 -0.113320737191137 6.28318530717959'/>
			<Background DEF='BG' skyColor="0.5 0.5 0.5"/>
			<NavigationInfo type='"EXAMINE" "ANY' speed="4" headlight="true"/>
			<DirectionalLight ambientIntensity="1" intensity="0" color="1 1 1"/>
			<Transform rotation='-0.734984397936391 0.477428228081317 0.481518661965676 1.71916544983595' scale='1 1 1' scaleOrientation='-0.373584715954867 -0.0259322116773033 -0.927233509102453 0.257019911109868'>
				<IsoSurfaceVolumeData
					dimensions='128 128 29'
					surfaceValues='0.5'
					bboxColor='1 0 0'
					bboxDisplay="true">
					<OpacityMapVolumeStyle/>
					<ImageTexture3D containerField='voxels'src='datasets/nrrd/HCG91_mJy_raw.nrrd'/>
				</IsoSurfaceVolumeData>
			</Transform>
		</Scene>
	</x3d></center>
</body>
</html>
```

Thanks,
Ixaka Labadie

**Comment by andreasplesch** [comment]
IsoSurfaeVolumeData works in principle but there are number of considerations.

1) Since this is html, not xml, use full closing tags for all nodes, starting with ```</Viewpoint>```. This should get rid of most errors.

2) NRRD unfortunately is not supported currently. You would need to reformat to an ImageTextureAtlas as source of voxels. This may be easy or hard depending on the raw data. There is also an older experimental branch with nrrd support here: https://github.com/andreasplesch/x3dom/tree/nrrd. See https://github.com/x3dom/x3dom/issues/807

3) You may need to supply an explicit transferFunction to OpacityMapVolumeStyle.

**Comment by ixakalabadie** [comment]
Thanks, it seems to work now, both with _VolumeData_ and _IsoSurfaceVolumeData_. As you said, an explicit _transferFunction_ is required. Here is the code:
```
<!DOCTYPE html>
	 <head>
		<script type='text/javascript' src='https://x3dom.org/download/dev/x3dom-full.js'></script>
		<link rel='stylesheet' type='text/css' href='https://x3dom.org/download/dev/x3dom.css'></link>
		<title> Stephan's Quintet</title>
	</head>
	<body>
		<h1> Stephan's Quintet </h1>
		<center><x3d showStat='true' showLog='false' width='100%' height='500px' id='cubeFixed'>
			<Scene>
				<Viewpoint description='HCG91' position='0 0 200' orientation='0 0 -0.113320737191137 6.28318530717959'></Viewpoint>
				<Background DEF='BG' skyColor="0.5 0.5 0.5"></Background>
				<NavigationInfo type='"EXAMINE" "ANY' speed="4" headlight="true"></NavigationInfo>
				<DirectionalLight ambientIntensity="1" intensity="0" color="1 1 1"></DirectionalLight>
				<Transform rotation='-0.734984397936391 0.477428228081317 0.481518661965676 1.71916544983595' scale='1 1 1' scaleOrientation='-0.373584715954867 -0.0259322116773033 -0.927233509102453 0.257019911109868'>
					<IsoSurfaceVolumeData
						dimensions='128 128 128'
						surfaceValues='0.22 0.4 0.6'>
						<ImageTextureAtlas containerField='voxels' url='hcg91image2d.png'
							numberOfSlices='58' slicesOverX='8' slicesOverY='8'></ImageTextureAtlas>
						<OpacityMapVolumeStyle>
							<ImageTexture containerField='transferFunction' url='transfer.png'></ImageTexture>
						</OpacityMapVolumeStyle>
					</IsoSurfaceVolumeData>
				</Transform>
			</Scene>
		</x3d></center>
	</body>
</html>
	
```

**Comment by andreasplesch** [comment]
Super. Glad you got it to work. Would it be possible to share a live scene ?

**Comment by andreasplesch** [comment]
Thanks:
https://andreasplesch.github.io/Library/Examples/html5/isosurface-volume-hcg91/isosurface.html
For numerical control, it should be possible to allow PixelTexture for the transferFunction:
https://github.com/x3dom/x3dom/blob/84a7caf91895ba6888b61a2870c6a9bfbf4c248a/src/nodes/VolumeRendering/OpacityMapVolumeStyle.js#L43

probably should be:

```js
 this.addField_SFNode( "transferFunction", x3dom.nodeTypes.X3DTextureNode ); 
```

and that may be all what is needed. But would require more extensive testing since the code seems to make assumption about the presence of an url field.

You can also use a data uri for ImageTexture, for a small 3x1 png for example.
