### ISSUE TITLE
Shape Resource Container (SRC) problem in X3DOM 1.7.2

### ISSUE THREAD

**Issue by bmegli** [x3dom/x3dom#695]
I have the following setup:

html head with (working):

``` html
    <script type='text/javascript' src='http://www.x3dom.org/download/1.7.1/x3dom.js'></script>
    <link rel='stylesheet' type='text/css' href='http://www.x3dom.org/download/1.7.1/x3dom.css'>
```

or with (not working):

``` html
    <script type='text/javascript' src='http://www.x3dom.org/download/1.7.2/x3dom.js'></script>
    <link rel='stylesheet' type='text/css' href='http://www.x3dom.org/download/1.7.2/x3dom.css'>
```

html body with:

``` html
 <x3d style="width: 100%; height: 40vh;">
    <scene>
       <inline url="some_url.x3d"></inline>
    </scene>
 </x3d>
```

the x3d file:

``` html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE X3D PUBLIC "ISO//Web3D//DTD X3D 3.0//EN" "http://www.web3d.org/specifications/x3d-3.0.dtd">
<X3D xmlns:xsd='http://www.w3.org/2001/XMLSchema-instance' profile='Full' version='3.0' xsd:noNamespaceSchemaLocation='http://www.web3d.org/specifications/x3d-3.0.xsd'>
  <Scene>
    <Viewpoint orientation='-0.17891 0.96316 0.20077 1.52241' position='1.44546 0.56506 0.13511'/>
    <Shape bboxCenter='0.526495 0.990452 -0.26578' bboxSize='5.00249 2.08094 6.57008'>
      <ExternalGeometry url='"some_url.src"'/>
    </Shape>
  </Scene>
</X3D>
```

And finally src file with binary geometry generated with `aopt`.

This works perfectly well with X3DOM 1.7.1.
In X3DOM 1.7.2 I get blank space where x3d models should be.

Nothing obvious comes in x3dom debug log (only INFO messages)

When I have more time I will make isolated example and put it on the web somewhere.

Has something changed with regard to SRC in 1.7.2 that I should know about?

Kind regards!

**Comment by bmegli** [comment]
The only difference that I see in log messages is that:

In 1.7.2:
``` 
[...]
INFO: NavType: undefined
INFO: Switch to examine mode.
[...]
```
Where in 1.7.1 I see:

``` 
[...]
INFO: NavType: examine
[...]
```

**Comment by bmegli** [comment]
More info from chrome console:
In 1.7.2 (this doesn't happen in 1.7.1):
``` 
Uncaught RangeError: Invalid typed array length
    at new Uint8Array (native)
    at x3dom.glTF.glTFLoader.readScene (https://www.x3dom.org/download/1.7.2/x3dom.js:863:17)
    at new x3dom.glTF.glTFLoader (https://www.x3dom.org/download/1.7.2/x3dom.js:817:109)
    at XMLHttpRequest.xhr.onload (https://www.x3dom.org/download/1.7.2/x3dom.js:4504:599)
```

**Comment by tsturm** [comment]
We merged a pull request which adds GLB support to the ExternalGeometry-Node.
It seems that this PR has broken the SRC loading.

We will try to fix this as far as possible.
 @skluge, @mlimper any ideas?

**Comment by bmegli** [comment]
@tsturm thanks for the info

I have isolated the problem here: [minimalistic examle](https://bmegli.github.io/x3dom-src-issue/). 

Info:
1. I used ball src0 file from official [x3dom src example](https://x3dom.org/src/exampleData/testingScene-SRC-1.6.html)
2. I have created 3 simple *html* files based on x3dom inline example, they only differ in x3dom version: [1.7.1](https://github.com/bmegli/x3dom-src-issue/blob/master/x3dom-1.7.1.html), [1.7.2](https://github.com/bmegli/x3dom-src-issue/blob/master/x3dom-1.7.2.html), [dev](https://github.com/bmegli/x3dom-src-issue/blob/master/x3dom-dev.html) 
3. The minimalistic [x3d file](https://github.com/bmegli/x3dom-src-issue/blob/master/src-input.x3d) is stripped down version of official x3dom src example (just one src object) 

You can see the problem *live* here:
- [1.7.1](https://bmegli.github.io/x3dom-src-issue/x3dom-1.7.1.html) works
- [1.7.2](https://bmegli.github.io/x3dom-src-issue/x3dom-1.7.2.html) nothing shows, error in chrome log
- [dev](https://bmegli.github.io/x3dom-src-issue/x3dom-dev.html) nothing shows, error in chrome log

The error shows in chrome log (Tools -> Developer Tools -> Log), not x3dom debug log and it is:
```
Uncaught RangeError: Invalid typed array length
    at new Uint8Array (native)
    at x3dom.glTF.glTFLoader.readScene (https://www.x3dom.org/download/1.7.2/x3dom.js:863:17)
    at new x3dom.glTF.glTFLoader (https://www.x3dom.org/download/1.7.2/x3dom.js:817:109)
    at XMLHttpRequest.xhr.onload (https://www.x3dom.org/download/1.7.2/x3dom.js:4504:599)
```

I observe the same symptoms in Edge, Firefox and Opera (I haven't checked their logs but what I see is the same).

Hopefully this can help.

P.S. - what is "the recommended way" for big geometries currently, src or glb or something else?

**Comment by mlimper** [comment]
> P.S. - what is "the recommended way" for big geometries currently, src or glb or something else?

Definitely glb!

aopt should be able to export glb containers instead of SRC, when you use "binaryGLTFVersion(1.0)" as part of the command line - could you give that a try?

I agree with @tsturm that this should be fixed somehow. However, that might take a while since everybody is going on holiday now... the mid-term goal is definitely to use glb, as glTF is now becoming the standard format across most engines and exporters.

**Comment by mlimper** [comment]
OK, small update:
I tried to add support for the "legacy" SRC format by using the old 1.7.1 code if the extension used is ".src" (https://github.com/x3dom/x3dom/commit/98d1a496e47ac356b7026b94556a7fa6aef537eb).

Unfortunately, it took a bit longer than expected, as it seems that the rendering code for both versions - glb, and the rest of X3DOM - is not 1:1 compatible with the old way SRC and other parts of X3DOM were specifying geometry for drawing. The result I got so far is a black sphere, so something might be wrong with the material, or with the normals (or both). Fixing this should be hopefully simple, as the ExternalGeometry should not influence the material at all, so as long as normals are loaded correctly this should be a "small" fix... but I got no time right now, so I pushed the state as-is.

**Comment by tsturm** [comment]
@mlimper Thanks for your efforts!

**Comment by bmegli** [comment]
> Definitely glb!

> aopt should be able to export glb containers instead of SRC, when you use "binaryGLTFVersion(1.0)" as part of the command line - could you give that a try?

Yes, knowing that this is the recommended way I will switch to glb now but it will also take me some time.
Thanks for this information.

It would be helpfull if x3dom had some clear recommendations.

It's not easy to figure out quickly which is the right way that should be used in new applications. There are numerous ways (this is good) to do everything in x3dom, like optimized binary geometry, src, glb, gltf.

Thanks for the small update, valuable info and kind regards!

**Comment by bmegli** [comment]
> aopt should be able to export glb containers instead of SRC, when you use "binaryGLTFVersion(1.0)" as part of the command line - could you give that a try?

I tried it and the toolchain aopt + x3dom works partially:

``` bash
aopt -i input_file.x3d -Y "binaryGLTFVersion(1.0)" -x output_with_glb.x3d
```

This generates glb files and x3d with no complaints.

When used on sample x3d from https://x3dom.org/src/:
- 2 models are rendered correctly by x3dom
- 3rd model doesn't show (it can be seen in x3dom debug mode so it's loaded) and I see in the chrome log:
```
[.Offscreen-For-WebGL-053B1AC0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 1
```
This error is triggered everytime mouse moves over x3dom.

This can be seen live [here](https://bmegli.github.io/x3dom-src-issue/) (under "Generated from testingScene.x3d")

--------------------------------------------------------------------------------

I also tried one of my models:
- it's converted to glb by aopt
- I get exceptions in the chrome log:

```
Uncaught TypeError: Cannot read property 'count' of undefined
    at x3dom.glTF.glTFLoader.loadglTFMesh (x3dom.js:849)
    at x3dom.glTF.glTFLoader.updateMesh (x3dom.js:836)
    at x3dom.glTF.glTFLoader.traverseNode (x3dom.js:835)
    at x3dom.glTF.glTFLoader.updateScene (x3dom.js:830)
    at x3dom.glTF.glTFLoader.getScene (x3dom.js:821)
    at XMLHttpRequest.xhr.onload (x3dom.js:3454)
x3dom.glTF.glTFLoader.loadglTFMesh @ x3dom.js:849
x3dom.glTF.glTFLoader.updateMesh @ x3dom.js:836
x3dom.glTF.glTFLoader.traverseNode @ x3dom.js:835
x3dom.glTF.glTFLoader.updateScene @ x3dom.js:830
x3dom.glTF.glTFLoader.getScene @ x3dom.js:821
xhr.onload @ x3dom.js:3454
x3dom.js:2460 Uncaught TypeError: Cannot read property 'length' of undefined
    at Context.x3dom.gfx_webgl.Context.renderPickingPass (x3dom.js:2460)
    at Context.x3dom.gfx_webgl.Context.pickValue (x3dom.js:2624)
    at x3dom.X3DDocument.onMouseOver (x3dom.js:1298)
    at HTMLCanvasElement.onMouseOver (x3dom.js:989)
```

But maybe my point clouds are not valid for glb for some reason (no triangles there, just points).

This also can be seen live [here](https://bmegli.github.io/x3dom-src-issue/) (under "Some of my models" header)

--------------------------------------------------------------------------

I am not complaining, just reporting an issue. X3DOM is great framework.

Kind regards.

P.S. I can move glb loading to separate issue

**Comment by skluge** [comment]
I took a look into the shading problem with the SRC file format and it really seems to be a problem with the normals. When using the normal-independant emissiveColor attribute, the shape is colored correct, so the shader works.

I will see if i can fix this.

**Comment by skluge** [comment]
Hi @bmegli  
i have fixed your problems with the Src compatibility and the glTF loading and rendering and made two pull requests with the fixes. Your test scenes were a big help and should be working now.

A note for the crime scene pointcloud. The glTF contains no material, so for a correct rendering you should use the ExternalGeometry Node inside a shape Node with an x3dom-Material for correct Rendering, else the pointcloud would not be visible.

Now we only have to wait until @mlimper or @tsturm accept the pull request.

**Comment by mlimper** [comment]
Thanks for the fix! I have merged your PRs.

@bmegli 
Can you check / confirm if the rendering issues with SRC and GLB are all fixed now?

**Comment by bmegli** [comment]
@skluge Thanks!

This a big leap forward, but not everything seems to be working yet.

1. Test scene from https://x3dom.org/src/ **works correctly** with glb now
2. PointCloud is **now loaded correctly** (fixed!) but I am unable to set color/material in any way for the points

I have tried so far:
- adding shape/apperance/material and using ExternalGeometry
- adding shape/apperance/material to x3d before converting to glb with aopt
- adding shape/appearance/material along with ColorRGBA for each vertex in PointSet before converting to glb
- the previous along with the first

Neither of those changes material/color of points.

This can be seen live:
- [here](https://bmegli.github.io/x3dom-src-issue/) (x3dom crime glb in dev).
- the [x3d](https://github.com/bmegli/x3dom-src-issue/blob/master/crime_sceneGLB.x3d) used
- this is as my last try so glb from x3d with material and per vertex ColorRGBA then also in shape with material as externalgeometry
- I set the background colour to gray so that black points are visible

I am using x3d [PointSet](https://doc.x3dom.org/author/Rendering/PointSet.html) so maybe it's something related to PointSet rendering or materials.

Kind regards!

**Comment by skluge** [comment]
Hi @bmegli,
when using the ExternalGeometry-Node with a Material-Node, you have have to set the emissiveColor. Since the points don't have normal-values, they are not influenced by lighting and thus the diffuse color has no effect.
Example for crime_sceneGLB.x3d:
```
<Shape>
  <Appearance>
    <Material emissiveColor="1 1 1" ></Material>
  </Appearance>
  <ExternalGeometry bboxCenter='0.526495 0.990452 -0.26578' bboxSize='5.00249 2.08094 6.57008' url='"crime_scene.glb"'></ExternalGeometry>
</Shape>
```

**Comment by bmegli** [comment]
Hi @skluge!

Your hint solves my personal problem in glb, thank you.

Summing up (glb in dev):
- original x3dom testing scene (for src) **works** when converted to glb with aopt
- x3dom **loads correctly** [PointSet](https://doc.x3dom.org/author/Rendering/PointSet.html), color has to be set through Appearance/Material/emmisiveColor
- [PointSet](https://doc.x3dom.org/author/Rendering/PointSet.html) color field (per vertex) is not used in glb (I don't know if it should, was working in src in 1.7.1)

Summing up (src in dev):
- x3dom testing scene (for src) **works** now, live [here](https://bmegli.github.io/x3dom-src-issue/x3dom-src-dev.html) (added now)
- x3dom [PointSet](https://doc.x3dom.org/author/Rendering/PointSet.html) **doesn't load**, at least for my data, live [here](https://bmegli.github.io/x3dom-src-issue/x3dom-src-crime-dev.html) (added now)

The last one with:
```
.Offscreen-For-WebGL-043A3238]RENDER WARNING: Render count or primcount is 0
```
 
All the testing scenes are live [here](https://bmegli.github.io/x3dom-src-issue/)
All the testing data can be found [here](https://github.com/bmegli/x3dom-src-issue)

**Comment by mlimper** [comment]
Does that mean we could render per-point colors before, but not any more?

**Comment by bmegli** [comment]
@mlimper, ok I am sorry for the confusion

> Does that mean we could render per-point colors before, but not any more?

For inline x3d (not src or glb):
- per color rendering for PointSet **works** in [1.7.1](https://bmegli.github.io/x3dom-src-issue/x3dom-direct-crime-1.7.1.html) and [dev](https://bmegli.github.io/x3dom-src-issue/x3dom-direct-crime-dev.html) (half gray half white)

For src or glb  through aopt toolchain:
- per color rendering doesn't work

But I believe that src or glb converted with aopt doesn't have color information. I infer this from fact that src converted from half-gray-half-white x3d doesn't differ (binary wise) from src converted from all white vertices.

I am sorry for the confusion. I was mocked up by the fact that my scene had all vertices white and this was what I got in src in 1.7.1. This made me think that per vertex colouring worked with aopt + x3dom src toolchain.

So if this behaviour is intentional the only thing that is not working still is:
- x3dom src [PointSet](https://doc.x3dom.org/author/Rendering/PointSet.html) **doesn't load**, at least for my data, live [here](https://bmegli.github.io/x3dom-src-issue/x3dom-src-crime-dev.html) 

All the testing scenes are live [here](https://bmegli.github.io/x3dom-src-issue/)
All the testing data can be found [here](https://github.com/bmegli/x3dom-src-issue)

**Comment by mlimper** [comment]
> But I believe that src or glb converted with aopt doesn't have color information.

I see - then we should check this in aopt.
One aim with glb is that other glb generation tools can be used as well (such as gltf-pipeline) - maybe that's also an interesting point.

**Comment by doczoidberg** [comment]
I am a bit late..

> x3dom src PointSet doesn't load, at least for my data, live here
gltf loader doesn't support points or lines. That should be the reason. I tried to convert your example files with current (dev) aopt tool from the instant reality homepage without success btw.
